### ISSUE TITLE
Plans for merging with ungit

### ISSUE THREAD

**Issue by jpschewe** [exsilium/mungit#12]
Now that ungit has gone back to MIT license, are there plans to merge this repository back to the ungit repository?

**Comment by exsilium** [comment]
I've reattached this repo to the ungit network in Github and although personally I'm still using the mungit fork (for the colors and the token auth), for everybody else, it makes sense to use ungit instead.

as that is where the active development is. Are there specific changes that you'd like to see in the ungit repo? I can definitely create separate PRs about these and see if they will be pulled.

**Comment by jpschewe** [comment]
OK, I'm in the process of switching back to ungit. I haven't noticed anything yet in mungit that's missing from ungit, but thought if you had any fixes those should be pulled over.

**Comment by exsilium** [comment]
Currently planning to keep this fork around mainly for personal use. Cheers! 🍻
