### ISSUE TITLE
Create annotated tag

### ISSUE THREAD

**Issue by jpschewe** [exsilium/mungit#7]
Is there a way to create an annotated tag in mungit or do I still need to use the command line for that?

**Comment by exsilium** [comment]
Actually, all the created tags through the graph interface are created as annotated tags (with the `-a` flag):
https://github.com/exsilium/mungit/blob/f5ec070eb433d2643fdd977a4dae7fb81adcb1a2/source/git-api.js#L389

You can check the created tags via `git show-ref -d --tags`. Annotated tags will have double entries present.

**Comment by jpschewe** [comment]
OK, sorry. I was just thrown by not being asked for a comment.
